# fly.toml app configuration file generated for whitees on 2023-11-11T13:22:44+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "whitees"
primary_region = "sin"

[build]
  image = "cathleyson/whitees:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  CloudinarySettings__ApiKey = "361478783915649"
  CloudinarySettings__CloudName = "dr04ygceb"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
